# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_region', models.CharField(max_length=100)),
                ('parameter_country', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'датасеты',
                'db_table': 'dataset',
            },
        ),
    ]
